os:
    - linux

env:
    - VIVTESTFILES=/tmp/vivtestfiles

sudo: required
dist: trusty

language: python

python:
    - "2.7_with_system_site_packages"

install:
    - "travis_retry sudo apt-get update"
    - git clone https://github.com/vivisect/vivtestfiles.git /tmp/vivtestfiles
    - "travis_retry sudo apt-get -qq install libfreetype6-dev liblcms2-dev python-qt4 ghostscript libffi-dev libjpeg-turbo-progs cmake imagemagick"
    - pip install msgpack-python

script: python -m unittest discover
